[mysqld]
basedir=.
datadir=./data
port=3306
max_connections=200
character-set-server=utf8mb4
default-storage-engine=INNODB
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
log-error=../core/logs/mysql.log
[client]
port=3306
default-character-set=utf8mb4
